INSERT INTO news_articles (title, content, author, published_date, category, tags, slug, meta_description, status, created_at, updated_at) VALUES
('Weekly Pairs in Focus - May 11 - May 16, 2025 (Charts)', 'Content from article_103', 'Broker Analysis', '2024-01-15', 'General', ARRAY['migration', 'article'], 'article-103', 'Article article_103 migrated from DailyForex', 'published', NOW(), NOW()),
('Weekly Pairs in Focus - May 18 - May 23, 2025 (Charts)', 'Content from article_104', 'Broker Analysis', '2024-01-15', 'General', ARRAY['migration', 'article'], 'article-104', 'Article article_104 migrated from DailyForex', 'published', NOW(), NOW()),
('Weekly Pairs in Focus - May 04 - May 10, 2025 (Charts)', 'Content from article_105', 'Broker Analysis', '2024-01-15', 'General', ARRAY['migration', 'article'], 'article-105', 'Article article_105 migrated from DailyForex', 'published', NOW(), NOW()),
('Weekly Forex Forecast - May 04th - May 10th (Charts)', 'Content from article_106', 'Broker Analysis', '2024-01-15', 'General', ARRAY['migration', 'article'], 'article-106', 'Article article_106 migrated from DailyForex', 'published', NOW(), NOW()),
('Weekly Forex Forecast - May 11th - May 16th (Charts)', 'Content from article_107', 'Broker Analysis', '2024-01-15', 'General', ARRAY['migration', 'article'], 'article-107', 'Article article_107 migrated from DailyForex', 'published', NOW(), NOW()),
('Weekly Forex Forecast - May 18th - May 23th (Charts)', 'Content from article_108', 'Broker Analysis', '2024-01-15', 'General', ARRAY['migration', 'article'], 'article-108', 'Article article_108 migrated from DailyForex', 'published', NOW(), NOW()),
('Weekly Forex Forecast - May 25th - May 30th (Charts)', 'Content from article_109', 'Broker Analysis', '2024-01-15', 'General', ARRAY['migration', 'article'], 'article-109', 'Article article_109 migrated from DailyForex', 'published', NOW(), NOW()),
('Bitcoin Price Today 10/06: Eyes 50% Rally (Chart)', 'Content from article_110', 'Broker Analysis', '2024-01-15', 'General', ARRAY['migration', 'article'], 'article-110', 'Article article_110 migrated from DailyForex', 'published', NOW(), NOW()),
('Crude Oil Monthly Forecast: July 2025 (Chart)', 'Content from article_111', 'Broker Analysis', '2024-01-15', 'General', ARRAY['migration', 'article'], 'article-111', 'Article article_111 migrated from DailyForex', 'published', NOW(), NOW()),
('Ethereum Analyst Projects $10K ETH in 2025: Here’s Why', 'Content from article_112', 'Broker Analysis', '2024-01-15', 'General', ARRAY['migration', 'article'], 'article-112', 'Article article_112 migrated from DailyForex', 'published', NOW(), NOW());