INSERT INTO news_articles (title, content, author, published_date, category, tags, slug, meta_description, status, created_at, updated_at) VALUES
('Alpari Launches Redesigned Trading Platform', 'Content from article_081', 'Broker Analysis', '2024-01-15', 'General', ARRAY['migration', 'article'], 'article-081', 'Article article_081 migrated from DailyForex', 'published', NOW(), NOW()),
('CFI Financial Appoints Omar Khaled as Global CMO', 'Content from article_082', 'Broker Analysis', '2024-01-15', 'General', ARRAY['migration', 'article'], 'article-082', 'Article article_082 migrated from DailyForex', 'published', NOW(), NOW()),
('Doo Prime Reveals New Identity to Lead the Future of Fintech', 'Content from article_083', 'Broker Analysis', '2024-01-15', 'General', ARRAY['migration', 'article'], 'article-083', 'Article article_083 migrated from DailyForex', 'published', NOW(), NOW()),
('FPFX Tech Celebrates Five Years of Fintech Innovation', 'Content from article_084', 'Broker Analysis', '2024-01-15', 'General', ARRAY['migration', 'article'], 'article-084', 'Article article_084 migrated from DailyForex', 'published', NOW(), NOW()),
('IronFX Celebrates 15 Years of Global Trading Excellence', 'Content from article_085', 'Broker Analysis', '2024-01-15', 'General', ARRAY['migration', 'article'], 'article-085', 'Article article_085 migrated from DailyForex', 'published', NOW(), NOW()),
('PU Prime Copy & Earn — Where Copying Means Cash!', 'Content from article_086', 'Broker Analysis', '2024-01-15', 'General', ARRAY['migration', 'article'], 'article-086', 'Article article_086 migrated from DailyForex', 'published', NOW(), NOW()),
('WikiFX Releases 2025 Malaysia SkyLine Guide', 'Content from article_087', 'Broker Analysis', '2024-01-15', 'General', ARRAY['migration', 'article'], 'article-087', 'Article article_087 migrated from DailyForex', 'published', NOW(), NOW()),
('Forex Today: Markets Expect US Inflation Unchanged Today', 'Content from article_088', 'Broker Analysis', '2024-01-15', 'General', ARRAY['migration', 'article'], 'article-088', 'Article article_088 migrated from DailyForex', 'published', NOW(), NOW()),
('US Inflation Unchanged but Core CPI Accelerates', 'Content from article_089', 'Broker Analysis', '2024-01-15', 'General', ARRAY['migration', 'article'], 'article-089', 'Article article_089 migrated from DailyForex', 'published', NOW(), NOW()),
('USD/TRY Forecast Today 25/11: Lira Stable (Chart)', 'Content from article_090', 'Broker Analysis', '2024-01-15', 'General', ARRAY['migration', 'article'], 'article-090', 'Article article_090 migrated from DailyForex', 'published', NOW(), NOW());