INSERT INTO news_articles (title, content, author, published_date, category, tags, slug, meta_description, status, created_at, updated_at) VALUES
('USD/TRY Forecast Today 04/11: Inflation Falls (Chart)', 'Content from article_091', 'Broker Analysis', '2024-01-15', 'General', ARRAY['migration', 'article'], 'article-091', 'Article article_091 migrated from DailyForex', 'published', NOW(), NOW()),
('USD/TRY Forecast 06/01: Lira Stabilizes on Support (Chart)', 'Content from article_092', 'Broker Analysis', '2024-01-15', 'General', ARRAY['migration', 'article'], 'article-092', 'Article article_092 migrated from DailyForex', 'published', NOW(), NOW()),
('USD/TRY Forecast Today 02/01: All Time Low (Chart)', 'Content from article_093', 'Broker Analysis', '2024-01-15', 'General', ARRAY['migration', 'article'], 'article-093', 'Article article_093 migrated from DailyForex', 'published', NOW(), NOW()),
('USD/TRY Forecast Today - 23/01: Euro Rallies in Thin Liquid', 'Content from article_094', 'Broker Analysis', '2024-01-15', 'General', ARRAY['migration', 'article'], 'article-094', 'Article article_094 migrated from DailyForex', 'published', NOW(), NOW()),
('USD/TRY Forecast Today 09/01: Lira Soars in 2024 (Chart)', 'Content from article_095', 'Broker Analysis', '2024-01-15', 'General', ARRAY['migration', 'article'], 'article-095', 'Article article_095 migrated from DailyForex', 'published', NOW(), NOW()),
('USD/TRY Forecast Today 24/02: Weak as Hits New Highs (Chart)', 'Content from article_096', 'Broker Analysis', '2024-01-15', 'General', ARRAY['migration', 'article'], 'article-096', 'Article article_096 migrated from DailyForex', 'published', NOW(), NOW()),
('Weekly Pairs in Focus - April 20 - April 26, 2025 (Charts)', 'Content from article_097', 'Broker Analysis', '2024-01-15', 'General', ARRAY['migration', 'article'], 'article-097', 'Article article_097 migrated from DailyForex', 'published', NOW(), NOW()),
('Weekly Pairs in Focus - April 27 - May 03, 2025 (Charts)', 'Content from article_098', 'Broker Analysis', '2024-01-15', 'General', ARRAY['migration', 'article'], 'article-098', 'Article article_098 migrated from DailyForex', 'published', NOW(), NOW()),
('USD/TRY Today 10/04: Support the Lira with Over $42 B. Chart', 'Content from article_099', 'Broker Analysis', '2024-01-15', 'General', ARRAY['migration', 'article'], 'article-099', 'Article article_099 migrated from DailyForex', 'published', NOW(), NOW()),
('Weekly Pairs in Focus - May 25 - May 30, 2025 (Charts)', 'Content from article_102', 'Broker Analysis', '2024-01-15', 'General', ARRAY['migration', 'article'], 'article-102', 'Article article_102 migrated from DailyForex', 'published', NOW(), NOW());