INSERT INTO news_articles (title, content, author, published_date, category, tags, slug, meta_description, status, created_at, updated_at) VALUES
('CFI Becomes Official Online Trading Partner of Etihad Arena', 'Content from article_071', 'Broker Analysis', '2024-01-15', 'General', ARRAY['migration', 'article'], 'article-071', 'Article article_071 migrated from DailyForex', 'published', NOW(), NOW()),
('CFI Welcomes Maria Sharapova as Global Brand Ambassador', 'Content from article_072', 'Broker Analysis', '2024-01-15', 'General', ARRAY['migration', 'article'], 'article-072', 'Article article_072 migrated from DailyForex', 'published', NOW(), NOW()),
('iFX EXPO Asia 2025 Returns to Hong Kong', 'Content from article_073', 'Broker Analysis', '2024-01-15', 'General', ARRAY['migration', 'article'], 'article-073', 'Article article_073 migrated from DailyForex', 'published', NOW(), NOW()),
('iFX EXPO International 2025 Sets New Global Benchmark', 'Content from article_074', 'Broker Analysis', '2024-01-15', 'General', ARRAY['migration', 'article'], 'article-074', 'Article article_074 migrated from DailyForex', 'published', NOW(), NOW()),
('Libertex Powers Up Monaco GP Weekend', 'Content from article_075', 'Broker Analysis', '2024-01-15', 'General', ARRAY['migration', 'article'], 'article-075', 'Article article_075 migrated from DailyForex', 'published', NOW(), NOW()),
('PU Prime and Argentina Football Association Celebrate', 'Content from article_076', 'Broker Analysis', '2024-01-15', 'General', ARRAY['migration', 'article'], 'article-076', 'Article article_076 migrated from DailyForex', 'published', NOW(), NOW()),
('PU Prime Named Best Copy Trading Platform of 2025 by WikiFX', 'Content from article_077', 'Broker Analysis', '2024-01-15', 'General', ARRAY['migration', 'article'], 'article-077', 'Article article_077 migrated from DailyForex', 'published', NOW(), NOW()),
('Understanding trading costs & how PrimeXBT stands out', 'Content from article_078', 'Broker Analysis', '2024-01-15', 'General', ARRAY['migration', 'article'], 'article-078', 'Article article_078 migrated from DailyForex', 'published', NOW(), NOW()),
('XM Arabia Successfully Concludes Regional Sponsorship', 'Content from article_079', 'Broker Analysis', '2024-01-15', 'General', ARRAY['migration', 'article'], 'article-079', 'Article article_079 migrated from DailyForex', 'published', NOW(), NOW()),
('XM Gives Unlimited Trading Cashback for 15-Year Anniversary', 'Content from article_080', 'Broker Analysis', '2024-01-15', 'General', ARRAY['migration', 'article'], 'article-080', 'Article article_080 migrated from DailyForex', 'published', NOW(), NOW());