INSERT INTO news_articles (title, content, author, published_date, category, tags, slug, meta_description, status, created_at, updated_at) VALUES
('EUR/USD Analysis Today 26/6: Will Euro Rise Further? (Chart)', 'Content from article_113', 'Broker Analysis', '2024-01-15', 'General', ARRAY['migration', 'article'], 'article-113', 'Article article_113 migrated from DailyForex', 'published', NOW(), NOW()),
('EUR/USD Analysis Today 26/06: Selling Recommended (Chart)', 'Content from article_114', 'Broker Analysis', '2024-01-15', 'General', ARRAY['migration', 'article'], 'article-114', 'Article article_114 migrated from DailyForex', 'published', NOW(), NOW()),
('Gold Analysis Today 23/06: Will XAU/USD Rise (Chart)', 'Content from article_115', 'Broker Analysis', '2024-01-15', 'General', ARRAY['migration', 'article'], 'article-115', 'Article article_115 migrated from DailyForex', 'published', NOW(), NOW()),
('Gold Analysis Today 24/06: Face Profit-Taking (Chart)', 'Content from article_116', 'Broker Analysis', '2024-01-15', 'General', ARRAY['migration', 'article'], 'article-116', 'Article article_116 migrated from DailyForex', 'published', NOW(), NOW()),
('Gold Analysis: When Can Gold Be Bought Again? (Chart)', 'Content from article_117', 'Broker Analysis', '2024-01-15', 'General', ARRAY['migration', 'article'], 'article-117', 'Article article_117 migrated from DailyForex', 'published', NOW(), NOW()),
('Weekly Pairs in Focus - June 01 - June 06, 2025 (Charts)', 'Content from article_118', 'Broker Analysis', '2024-01-15', 'General', ARRAY['migration', 'article'], 'article-118', 'Article article_118 migrated from DailyForex', 'published', NOW(), NOW()),
('Weekly Pairs in Focus - June 08 - June 14, 2025 (Charts)', 'Content from article_119', 'Broker Analysis', '2024-01-15', 'General', ARRAY['migration', 'article'], 'article-119', 'Article article_119 migrated from DailyForex', 'published', NOW(), NOW()),
('Weekly Pairs in Focus - June 15 - June 21, 2025 (Charts)', 'Content from article_120', 'Broker Analysis', '2024-01-15', 'General', ARRAY['migration', 'article'], 'article-120', 'Article article_120 migrated from DailyForex', 'published', NOW(), NOW()),
('Weekly Pairs in Focus - June 22 - June 28, 2025 (Charts)', 'Content from article_121', 'Broker Analysis', '2024-01-15', 'General', ARRAY['migration', 'article'], 'article-121', 'Article article_121 migrated from DailyForex', 'published', NOW(), NOW()),
('Weekly Pairs in Focus - June 29 - July 05, 2025 (Charts)', 'Content from article_122', 'Broker Analysis', '2024-01-15', 'General', ARRAY['migration', 'article'], 'article-122', 'Article article_122 migrated from DailyForex', 'published', NOW(), NOW());