INSERT INTO news_articles (title, content, author, published_date, category, tags, slug, meta_description, status, created_at, updated_at) VALUES
('Why Every Country Is Racing to Launch a Central Bank Digital', 'Content from article_061', 'Broker Analysis', '2024-01-15', 'General', ARRAY['migration', 'article'], 'article-061', 'Article article_061 migrated from DailyForex', 'published', NOW(), NOW()),
('iFX EXPO: A Tour Around the World', 'Content from article_062', 'Broker Analysis', '2024-01-15', 'General', ARRAY['migration', 'article'], 'article-062', 'Article article_062 migrated from DailyForex', 'published', NOW(), NOW()),
('T4Trade: Trading Platform for Purpose-Driven Traders', 'Content from article_063', 'Broker Analysis', '2024-01-15', 'General', ARRAY['migration', 'article'], 'article-063', 'Article article_063 migrated from DailyForex', 'published', NOW(), NOW()),
('Last Chance To Nominate Your Candidate for the Industry’s', 'Content from article_064', 'Broker Analysis', '2024-01-15', 'General', ARRAY['migration', 'article'], 'article-064', 'Article article_064 migrated from DailyForex', 'published', NOW(), NOW()),
('PU Prime Clinches Two Prestigious Awards at Forex Sports', 'Content from article_065', 'Broker Analysis', '2024-01-15', 'General', ARRAY['migration', 'article'], 'article-065', 'Article article_065 migrated from DailyForex', 'published', NOW(), NOW()),
('Unlock Limitless Possibilities at iFX EXPO International', 'Content from article_066', 'Broker Analysis', '2024-01-15', 'General', ARRAY['migration', 'article'], 'article-066', 'Article article_066 migrated from DailyForex', 'published', NOW(), NOW()),
('Wiki Finance Expo Cyprus 2025', 'Content from article_067', 'Broker Analysis', '2024-01-15', 'General', ARRAY['migration', 'article'], 'article-067', 'Article article_067 migrated from DailyForex', 'published', NOW(), NOW()),
('CFI Financial Appoints Ziad Melhem as Group CEO', 'Content from article_068', 'Broker Analysis', '2024-01-15', 'General', ARRAY['migration', 'article'], 'article-068', 'Article article_068 migrated from DailyForex', 'published', NOW(), NOW()),
('How Market Volatility Affects Execution', 'Content from article_069', 'Broker Analysis', '2024-01-15', 'General', ARRAY['migration', 'article'], 'article-069', 'Article article_069 migrated from DailyForex', 'published', NOW(), NOW()),
('Trade W Officially Launches New Logo', 'Content from article_070', 'Broker Analysis', '2024-01-15', 'General', ARRAY['migration', 'article'], 'article-070', 'Article article_070 migrated from DailyForex', 'published', NOW(), NOW());