-- Individual article migration 128
INSERT INTO articles (title, slug, content, excerpt, category, subcategory, author_id, published_at, meta_description, meta_keywords, featured_image_url, status, view_count, tags, language) 
VALUES ('Weekly Forex Forecast - June 29th - July 05th (Charts)', 'weekly-forex-forecast---june-29th---july-05th-charts', 'Fundamental Analysis & Market SentimentI wrote on 22nd June that the best trades for the week would be:Long of the EUR/USD currency pair. This ended the week higher by 1.69%.Long of Gold in USD terms. This ended the week lower by 3.24%.Long of Silver in USD terms following a daily (New York) close above $37.13. This did not set up.Long of WTI Crude Oil if there is a daily (New York) close above $80.43. This did not set up.The overall loss of 1.55% equals a loss of 0.52% per asset.The news this week has been dominated by the clear Israeli / American victory over Iran, which ended with a US ceasefire last Tuesday morning. Both Israel and the Trump administration have been quite belligerent, threatening to resume bombing if Iran acts to rebuild its nuclear and ballistic missile capabilities. The scale of the victory will certainly tilt the dynamics of the Middle East towards Israel and the USA, with the Trump administration hinting that further countries, possibly even including Syria, will shortly be joining the Abraham accords, i.e. making a formal peace with Israel.The aftermath of the war has seen risk assets, especially in the USA, increase in value, with major US stock market indices like the NASDAQ 100 and the S&P 500 breaking out to new all-time high prices, which is usually a very bullish sign.This bullish environment is interesting as it contradicts some economic data we got this week and what the Federal Reserve is saying, not to mention the 9th July Trump tariff deadline which is just around the corner.Jerome Powell, Chair of the Fed, has now led investors to expect three further rate cuts this year of 0.25% each, up from two.Final GDP data for the USA came in notably worse than expected, suggesting a recession might even be possible.Turning to the 9th July tariff deadline, the USA has concluded only two trade deals, meaning that if more deals are not inked over the next 10 days, the US will impose much higher tariffs on many countries. However, the White H'',
    ''Technical and fundamental outlook on Nasdaq 100, NVIDIA, S&P 500, USD/CHF, EUR/USD, GBP/USD, and Silver. Key setups for July 2025.'',
    ''weekly-forex-forecast-june-29th-july-05th-charts'',
    ''General'',
    ''Broker Analysis'',
    NULL,
    ''published'',
    ''2025-08-21T13:03:49.594028'',
    ''2025-08-21T13:03:49.594046'',
    ''C:\Users\LENOVO\Desktop\BrokeranalysisDaily\daily forex\www.dailyforex.com\forex-technical-analysis\2025\06\weekly-forex-forecast-29th-june-to-5th-july-2025\230376.html'',
    ''Technical and fundamental outlook on Nasdaq 100, NVIDIA, S&P 500, USD/CHF, EUR/USD, GBP/USD, and Silver. Key setups for July 2025.', 'Fundamental Analysis & Market SentimentI wrote on 22nd June that the best trades for the week would be:Long of the EUR/USD currency pair. This ended the week higher by 1.69%.Long of Gold in USD terms....', 'Forex', NULL, (SELECT id FROM authors WHERE name = 'Broker Analysis' LIMIT 1), '2025-06-01 10:00:00+00', 'Fundamental Analysis & Market SentimentI wrote on 22nd June that the best trades for the week would be:Long of the EUR/USD currency pair. This ended the week higher by 1.69%.Long of Gold in USD terms....', 'forex, currency analysis, weekly analysis, forecast', NULL, 'published', 0, ARRAY['forex', 'currency analysis', 'weekly analysis', 'forecast'], 'en');