-- Individual article migration 161
INSERT INTO articles (title, slug, content, excerpt, category, subcategory, author_id, published_at, meta_description, meta_keywords, featured_image_url, status, view_count, tags, language) 
VALUES ('Weekly Forex Forecast - July 06th - July 12th (Charts)', 'weekly-forex-forecast---july-06th---july-12th-charts', 'Fundamental Analysis & Market SentimentI wrote on 29th June that the best trades for the week would be:Long of the EUR/USD currency pair. This ended the week higher by 0.46%.Long of the NASDAQ 100 Index. This ended the week higher by 1.03%.Long of NVIDIA. This ended the week higher by 0.59%.Long of Silver in USD terms following a daily (New York) close above $37.25. This did not set up.The overall win of 2.08% equals a gain of 0.52% per asset.The news last week was dominated by positive risk-on sentiment continuing in US markets, which lifted both major US equity indices to new record highs, possibly boosted by the passage of President Trump’s flagship spending bill. The bill had looked in danger, but it was eventually pushed through both Houses of Congress. This is a win for President Trump, although the bill has been criticized as fiscally irresponsible by many on the right.Sentiment was certainly boosted by the much stronger jobs and average hourly earnings data released in the USA on Thursday, which sent stock markets soaring as the data showed a much stronger than expected economy.Although sentiment was risk-on last week, the sentiment is showing signs of slowing, and this is probably because Trump’s tariffs are now starting to come back into focus, with the coming Wednesday 9th July being Trump’s deadline for trade deals or higher tariffs, although President Trump has indicated he might extend the deadline again for at least some countries.It does seem likely that President Trump will announce the exact rates of steeper tariffs which will start to apply Wednesday from early next week, and where there are no deal or bad deals, we could see some volatility in the stock markets and currencies of those countries, as we did earlier in 2025 when Trump’s higher tariffs first started being imposed..Other market drivers last week related to certain high-impact data releases:US Average Hourly Earnings – this was expected to show a lower month-on-month increase of only 0'',
    ''Top trades: EUR/USD, NASDAQ 100, S&P 500, Silver. Key events: Trump’s tariff deadline, RBA rate cut, FOMC minutes. Markets near record highs.'',
    ''weekly-forex-forecast-july-06th-july-12th-charts'',
    ''General'',
    ''Broker Analysis'',
    NULL,
    ''published'',
    ''2025-08-21T13:04:07.577224'',
    ''2025-08-21T13:04:07.577235'',
    ''C:\Users\LENOVO\Desktop\BrokeranalysisDaily\daily forex\www.dailyforex.com\forex-technical-analysis\2025\07\weekly-forex-forecast-06th-july-to-12th-july-2025\230742.html'',
    ''Top trades: EUR/USD, NASDAQ 100, S&P 500, Silver. Key events: Trump’s tariff deadline, RBA rate cut, FOMC minutes. Markets near record highs.', 'Fundamental Analysis & Market SentimentI wrote on 29th June that the best trades for the week would be:Long of the EUR/USD currency pair. This ended the week higher by 0.46%.Long of the NASDAQ 100 Ind...', 'Forex', NULL, (SELECT id FROM authors WHERE name = 'Broker Analysis' LIMIT 1), '2025-06-01 10:00:00+00', 'Fundamental Analysis & Market SentimentI wrote on 29th June that the best trades for the week would be:Long of the EUR/USD currency pair. This ended the week higher by 0.46%.Long of the NASDAQ 100 Ind...', 'forex, currency analysis, weekly analysis, forecast', NULL, 'published', 0, ARRAY['forex', 'currency analysis', 'weekly analysis', 'forecast'], 'en');