INSERT INTO news_articles (
    title, content, summary, slug, category, author, 
    published_date, status, created_at, updated_at, 
    source_file, meta_description
) VALUES
('US and Canadian Inflation Accelerates - 15/07',
    'The markets were braced for a rebound in June inflation in Canada and the US and that’s exactly what happened today in both countries, as CPI and core CPI climbed higher.US CPI, Core CPI Hotter in JuneThe US consumer price index (CPI) rose 2.7% year-on year in June, up from 2.4% in May, matching the consensus expectation. This was the second consecutive monthly rise in inflation, which is now at its highest level since February 2025. On a month-on-month basis, CPI rose to 0.3% from 0.1% in May, the largest increase in five months and matching the consensus.Core CPI, which excludes food and energy and is considered a better gauge of inflation trends, climbed to 2.9% from 2.8% but below the consensus of 3.0%. Monthly, the core rate rose 0.3%, up from 0.1% in May and matched the consensus.The hotter June inflation numbers were most likely driven by President Trump’s tariffs, which have raised the price on most products imported into the US. The tariffs, which were first imposed in April, did not show a spike in inflation until now and we can expect upcoming that the tariffs will also be felt in upcoming inflation reports as the tariffs continue to filter through the US economy.Today’s hot inflation report means pressure on the Federal Reserve to lower rates will ease. The money markets have priced a hold at the July 30 meeting at close to 100%, although the Fed is expected to resume cutting rates in the fourth quarter.Top Forex Brokers1Get Started74% of retail CFD accounts lose moneyRead ReviewCanada’s CPI Hits 1.9%Canada’s inflation rate also heated up in June. CPI rose to 1.9% year-on-year, up from 1.7% in May and in line with the consensus. Inflation remained below the Bank of Canada’s target rate of 2% for a third successive month. Monthly, CPI dropped to 0.1%, compared to 0.6% in May and matching the consensus expectation. The trimmed-mean core CPI, which the BoC uses as its preferred gauge for underlying inflation, was unchanged at 3% y/y, as expected. BoC policymakers won’t be losing any sleep over headline CPI, which remains below the 2% target, but would like to see core CPI ease before delivering a rate cut.US Dollar Shows Muted Reaction, US Stock Market Edges Higher After Inflation ReportThe US dollar is showing limited in the aftermath of today’s inflation report. TheEUR/USD currency pairandGBP/USDare showing almost no change today.USD/JPYis up 0.34%, trading at 148.14.USD/CADhas weakened slightly following the US and Canadian inflation reports and is down 0.08% on the day, trading at 1.3693.The US stock market has only been open for a short time and is showing slight gains.TheS&P 500 Indexis up 13.8 points (0.22%) and is currently trading at 6,280.TheNasdaq 100 Indexhas gained 133.3 points (0.65%) and is currently trading at 20,773.',
    'US, Canada CPI rise in June; US hits 2.7%, core 2.9%. Tariffs blamed. Fed likely on hold. Stocks up, USD steady. Nasdaq +0.65%, S&P 500 +0.22%.',
    'us-and-canadian-inflation-accelerates-1507',
    'General',
    'Broker Analysis',
    NULL,
    'published',
    '2025-08-20T11:27:12.633725',
    '2025-08-20T11:27:12.633733',
    'C:\Users\LENOVO\Desktop\BrokeranalysisDaily\daily forex\www.brokeranalysis.com\forex-news\2025\07\us-and-canadian-inflation-accelerates-15-july-2025\231250.html',
    'US, Canada CPI rise in June; US hits 2.7%, core 2.9%. Tariffs blamed. Fed likely on hold. Stocks up, USD steady. Nasdaq +0.65%, S&P 500 +0.22%.');