INSERT INTO news_articles (
    title, content, summary, slug, category, author, 
    published_date, status, created_at, updated_at, 
    source_file, meta_description
) VALUES
('Forex Today: Markets Expect US Inflation Unchanged Today',
    'Top Forex Brokers1Get Started74% of retail CFD accounts lose moneyRead ReviewThe focus will shift today to the release of US CPI (inflation) data, with the annualized rate expected to remain unchanged.Markets will be focusing today on the upcoming release of US CPI (inflation) data. It is widely expected that the annualized rate will remain unchanged at 2.4%, with month-on-month CPI expected to show an increase of 0.3%. If the data is higher than expected, that could boost the USD and sink US stocks; if lower than expected, the opposite will be likely.The big news yesterday was the announcement of a trade deal between the USA and China, who have been engaged in a noisy and destructive trade war since Trump took office in January. It was agreed that during an upcoming 90-day period for further negotiations, the US would drop tariffs on Chinese imports from 145% to 30%, while China would drop tariffs on US imports from 125% to 10%. The US Dollar and US stock markets immediately jumped and held these increases, withthe NASDAQ 100 Indexup by 4.4% on the day andthe S&P 500 Indexclosing higher by 3.3%. Asian stock markets have mostly continued this rally, although Chinese indices are trading lower today. This news is likely to be bullish for global risk-on sentiment generally, including stock markets.Following yesterday''s trade deal between the USA and China, markets are now expecting only 2 US rate cuts over the course of 2025, at 0.25% each, according tothe CME FedWatch tool. The first cut is not expected until September.In the Forex market, since today''s Tokyo open, the Australian Dollar has been the strongest major currency, while the USD has been the weakest, puttingthe AUD/USD currency pairin focus - the Aussie typically gains when global risk sentiment improves. However, it can be said that the USD strength we saw yesterday is likely to hold up over the coming days.Bitcoindropped quite sharply yesterday after coming close to testing its record high made a few months ago after making a bullish breakout beyond its former key resistance level at $95,206. This may be partly due to USD strength but can be seen as a sign that Bitcoin bullishness is muted, as other risky assets advanced yesterday on the trade deal news.There will be a release today of UK Claimant Count Change (unemployment claims) data.',
    'Markets are closely watching today''s US CPI release while a new US-China trade deal boosts global stock markets and dampens rate cut expectations.',
    'forex-today-markets-expect-us-inflation-unchanged-today',
    'General',
    'Broker Analysis',
    NULL,
    'published',
    '2025-08-20T11:26:22.308649',
    '2025-08-20T11:26:22.308657',
    'C:\Users\LENOVO\Desktop\BrokeranalysisDaily\daily forex\www.brokeranalysis.com\forex-news\2025\05\forex-today-13-may-2025\228184.html',
    'Markets are closely watching today''s US CPI release while a new US-China trade deal boosts global stock markets and dampens rate cut expectations.');